package reviewlanecmd

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
	"syscall"
	"time"

	"github.com/anoop2811/software-factory-template/internal/config"
	"github.com/anoop2811/software-factory-template/internal/fileinput"
	"github.com/anoop2811/software-factory-template/internal/filepublish"
	"github.com/anoop2811/software-factory-template/internal/output"
	"github.com/anoop2811/software-factory-template/internal/terminalinput"
)

func validSecret(value string) bool {
	if value == "" || value[0] >= '0' && value[0] <= '9' || strings.HasPrefix(strings.ToUpper(value), "GITHUB_") {
		return false
	}
	for _, c := range []byte(value) {
		valid := c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '_'
		if !valid {
			return false
		}
	}
	return true
}
func writableConfig(path string) error {
	info, err := os.Lstat(strings.TrimRight(path, "\n"))
	if errors.Is(err, os.ErrNotExist) {
		//nolint:revive,staticcheck // Preserve the legacy diagnostic: docs/adr/0089-go-native-review-lane.md:20.
		return fmt.Errorf("review lane: no %s — run 'factory init' first.\n  Nothing was written; the lane is still off.", path)
	}
	if err != nil {
		return err
	}
	if !safeFile(info) || info.Mode().Perm()&0200 == 0 {
		return errors.New("review lane: configuration must be a writable caller-owned regular file")
	}
	return syscall.Access(path, 2)
}
func modelAnswer(ctx context.Context, s Settings, out io.Writer, interactive bool) (string, error) {
	model := s.Values["REVIEW_MODEL"]
	if model != "" || !interactive || !isTerminal(out) {
		return model, nil
	}
	reader, err := terminalinput.Open(ctx)
	if err != nil {
		if ctx.Err() != nil {
			return "", ctx.Err()
		}
		return "", nil
	}
	defer reader.Close()
	prompt := "Review model — the reviewer runs at the frontier tier by default.\n  provider: " + s.value("MODEL_PROVIDER", "openrouter") + "\n  default: " + s.model() + "\n  Model to use (Enter for the default): "
	if err := output.WriteEvent(ctx, out, []byte(prompt)); err != nil {
		return "", err
	}
	line, err := bufio.NewReaderSize(io.LimitReader(reader, (64<<10)+2), (64<<10)+2).ReadString('\n')
	if len(line) > 64<<10 {
		return "", errors.New("review model answer exceeds 64 KiB")
	}
	if err != nil {
		if errors.Is(err, io.EOF) {
			return "", nil
		}
		return "", err
	}
	// Bash read strips its default IFS around a single answer, preserving literals.
	return strings.Trim(strings.TrimSuffix(line, "\n"), " \t"), nil
}

// Stage before settings and publish only after lane-on; failed publication rolls
// back with an independent bounded context. docs/adr/0089-go-native-review-lane.md:72.
func enable(ctx context.Context, root, template, path, secret string, s Settings, out, stderr io.Writer, interactive bool) (returned error) {
	source := pathAt(template, "packs/review-lane/review-pr.yml")
	data, err := fileinput.Read(ctx, source, fileLimit)
	if errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("review-lane: %s not found.\n  This repo predates the review lane. Pull it in with:\n    curl -fsSL https://softwareaifactory.sh/install.sh | sh -s -- upgrade", source)
	}
	if err != nil {
		return err
	}
	if !validSecret(secret) {
		return errors.New("review lane: invalid repository secret name")
	}
	model, err := modelAnswer(ctx, s, out, interactive)
	if err != nil {
		return err
	}
	if strings.ContainsAny(model, "\x00\r\n\"") {
		return errors.New("review lane: invalid review model value")
	}
	if err := writableConfig(path); err != nil {
		return err
	}
	marker := []byte("__REVIEW_API_KEY_SECRET__")
	count := bytes.Count(data, marker)
	if count == 0 {
		return errors.New("review lane: workflow template has no secret placeholder")
	}
	size := int64(len(managedHeader)+1+len(data)) + int64(count)*int64(len(secret)-len(marker))
	if size > fileLimit {
		return errors.New("review lane: generated workflow exceeds 16 MiB")
	}
	rendered := append([]byte(managedHeader+"\n"), bytes.ReplaceAll(data, marker, []byte(secret))...)
	directory, err := openWorkflow(ctx, root, true)
	if err != nil {
		return err
	}
	defer func() { returned = errors.Join(returned, directory.close()) }()
	original, managed, err := directory.observe(ctx)
	if err != nil {
		return err
	}
	if original != nil && !managed {
		//nolint:revive,staticcheck // Preserve the legacy diagnostic: docs/adr/0089-go-native-review-lane.md:20.
		return fmt.Errorf("review lane: %s already exists and was not generated by the factory.\n  Move or remove it first — refusing to overwrite a workflow you own.", pathAt(root, workflow))
	}
	if err := directory.check(ctx); err != nil {
		return err
	}
	stage, err := filepublish.Prepare(ctx, directory.directory(), ".adversarial-review.", rendered, 0644)
	if err != nil {
		return err
	}
	defer func() { returned = errors.Join(returned, stage.Cleanup()) }()
	for _, entry := range [][2]string{{"review_api_key_secret", secret}, {"review_model", model}, {"review_lane", "on"}} {
		if err := config.Set(ctx, path, entry[0], entry[1]); err != nil {
			return err
		}
	}
	err = directory.unchanged(ctx, original)
	if err == nil {
		err = stage.Publish(ctx, "adversarial-review.yml")
	}
	if err != nil {
		rollback, cancel := context.WithTimeout(context.WithoutCancel(ctx), 5*time.Second)
		defer cancel()
		rollbackErr := config.Set(rollback, path, "review_lane", "off")
		message := "review lane: could not install " + pathAt(root, workflow) + ".\n"
		if rollbackErr == nil {
			message += "  Rolled the lane back to off; workflow publication did not succeed.\n"
		} else {
			message += "  The lane could not be rolled back either — run 'factory review-lane disable'.\n"
		}
		writeErr := output.WriteEvent(rollback, stderr, []byte(message))
		return errors.Join(err, rollbackErr, writeErr)
	}
	return enabledMessage(ctx, out, s, secret, model, interactive)
}
func disable(ctx context.Context, root, path string, stderr, out io.Writer) (returned error) {
	if err := writableConfig(path); err != nil {
		return err
	}
	directory, err := openWorkflow(ctx, root, false)
	if err != nil {
		return err
	}
	defer func() { returned = errors.Join(returned, directory.close()) }()
	original, managed, err := directory.observe(ctx)
	if err != nil {
		return err
	}
	if original != nil && !managed {
		if err := output.WriteEvent(ctx, stderr, []byte("review lane: "+pathAt(root, workflow)+" was not generated by the factory — leaving it.\n")); err != nil {
			return err
		}
		if err := config.Set(ctx, path, "review_lane", "off"); err != nil {
			return err
		}
		//nolint:revive,staticcheck // Preserve the legacy diagnostic: docs/adr/0089-go-native-review-lane.md:20.
		return errors.New("review lane: marked off in factory.yaml; remove that file yourself if you meant to.")
	}
	if err := directory.unchanged(ctx, original); err != nil {
		return err
	}
	if original != nil {
		if err := directory.directory().Remove("adversarial-review.yml"); err != nil {
			return err
		}
	}
	if err := config.Set(ctx, path, "review_lane", "off"); err != nil {
		return err
	}
	return output.WriteEvent(ctx, out, []byte("review lane: disabled (workflow removed; nothing runs on your PRs).\n"))
}
func enabledMessage(ctx context.Context, out io.Writer, s Settings, secret, model string, interactive bool) error {
	if model == "" {
		model = s.model() + " (frontier tier)"
	}
	yellow, bold, reset := "", "", ""
	if interactive && isTerminal(out) && s.Values["NO_COLOR"] == "" {
		yellow = "\x1b[33m"
		bold = "\x1b[1m"
		reset = "\x1b[0m"
	}
	message := "review lane: enabled.\n  model:  " + model + "\n\n  It runs a model over the diff of every pull request and posts an\n  advisory comment. That costs tokens on each PR — the reviewer is\n  deliberately the frontier tier, so it is the expensive one.\n\n"
	message += yellow + bold + "┌─ Action required — the lane cannot work without this " + reset + "\n"
	for _, line := range []string{"Add a repository secret named " + bold + secret + reset, "GitHub -> Settings -> Secrets and variables -> Actions -> New repository secret", "Value: your " + s.value("MODEL_PROVIDER", "openrouter") + " API key"} {
		message += yellow + "│" + reset + " " + line + "\n"
	}
	message += yellow + "└─" + reset + "\n\n  It is advisory only and never a required check. Turn it off any time\n  with: ./factory review-lane disable\n"
	return output.WriteEvent(ctx, out, []byte(message))
}
